import type { NextRequest } from 'next/server';

import { deepseek as deepseekProvider } from '@ai-sdk/deepseek';
import { generateText } from 'ai';
import { NextResponse } from 'next/server';

import { DEEPSEEK_CHAT_MODEL } from '@/lib/ai/deepseek';

export async function POST(req: NextRequest) {
  const {
    apiKey: key,
    model = DEEPSEEK_CHAT_MODEL,
    prompt,
    system,
  } = await req.json();

  const apiKey = key || process.env.DEEPSEEK_API_KEY;

  if (!apiKey) {
    return NextResponse.json(
      { error: 'Missing DeepSeek API key.' },
      { status: 401 }
    );
  }

  try {
    const { text } = await generateText({
      abortSignal: req.signal,
      maxOutputTokens: 100,
      model: deepseekProvider(model || DEEPSEEK_CHAT_MODEL),
      prompt,
      system,
      temperature: 0.7,
    });

    if (!text) {
      return NextResponse.json(
        { error: 'No text generated by model.' },
        { status: 502 }
      );
    }

    return NextResponse.json({ text });
  } catch (error) {
    console.error('Copilot error', {
      error,
      hasSignal: !!req.signal,
      model,
      baseURL: process.env.DEEPSEEK_BASE_URL,
    });
    if (error instanceof Error && error.name === 'AbortError') {
      return NextResponse.json(null, { status: 408 });
    }

    return NextResponse.json(
      { error: 'Failed to process AI request' },
      { status: 500 }
    );
  }
}
